version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-v:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: graymatics
      MYSQL_DATABASE: video_summarization
      MYSQL_USER: graymatics
      MYSQL_PASSWORD: graymatics

  video-summarization-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile-dev
    depends_on:
      - mysql
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- capabilities:
                #- gpu
    ports:
      - 3300:3300
    volumes:
      - ./video-summarization/Video_Summarization:/home/Video_Summarization
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  video-summarization-ui:
    build:
      context: ./
      dockerfile: ./client/Dockerfile-dev
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - /app/node_modules