version: "3"

networks:
  dev:
    external: true

services:
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql-v:/var/lib/mysql
    restart: always
    #network_mode: host
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: graymatics
      MYSQL_DATABASE: video_summarization
      MYSQL_USER: graymatics
      MYSQL_PASSWORD: graymatics

  video-summarization-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - mysql
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    network_mode: host
    #networks:
    #  - dev
    #ports:
    #  - 3300:3300
    volumes:
      - /home/ubuntu/Summarization/video-summarization/Video_Summarization:/home/Video_Summarization
    restart: always

  video-summarization-ui:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    restart: always
    networks:
      - dev
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
