FROM node
WORKDIR /usr/src/app
COPY server/package*.json ./
#RUN npm ci --only=production
RUN apt-get update || : && apt-get install python -y
RUN cd /tmp && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py && python get-pip.py
RUN pip install opencv-python==4.2.0.32
RUN apt-get update -y && apt-get install -y 
#python-mysqldb
RUN apt-get install -y software-properties-common && add-apt-repository ppa:mc3man/trusty-media -y || true  && pt-get update -y || true && apt-get install -y ffmpeg
RUN pip install python-dotenv
RUN pip install mysql-connector-python
#COPY mpeg1muxer.js node_modules/node-rtsp-stream
RUN npm install
WORKDIR /usr/src/darknet
RUN git clone https://github.com/pjreddie/darknet.git
WORKDIR /usr/src/darknet/darknet
RUN ls -l
RUN make
RUN apt-get install -y libopencv-dev
#WORKDIR /usr/src/darknet
#RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
#RUN dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
#RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
#RUN add-apt-repository --remove ppa:mc3man/trusty-media
#RUN apt-get update
#RUN wget http://security.ubuntu.com/ubuntu/pool/main/s/screen-resolution-extra/screen-resolution-extra_0.17.1_all.deb
#RUN dpkg -i screen-resolution-extra_0.17.1_all.deb
#RUN apt-get install -f
#RUN apt-get install -y nvidia-settings 
#RUN apt-get install -y cuda-10-0
WORKDIR /usr/src/app
COPY server/ .
EXPOSE 3300
CMD [ "npm", "start" ]
